# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  name: 'AspNetCoreSample'
  inputs:
    command: 'publish'
    publishWebProjects: false
    modifyOutputPath: false
    arguments: '--configuration $(buildConfiguration) -o $(Pipeline.Workspace)/publish/AspNetCoreSample'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/publish/AspNetCoreSample'
    artifact: 'AspNetCoreSample'
    publishLocation: 'pipeline'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Petteri - MSDN'
    appType: 'webApp'
    WebAppName: 'ubi-aspnet-core-sample'
    packageForLinux: '$(Pipeline.Workspace)/publish/AspNetCoreSample/**/*.zip'
