# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  project: 'AspNetCoreSample'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'publish'
    publishWebProjects: false
    modifyOutputPath: false
    arguments: '--configuration $(buildConfiguration) -o $(Pipeline.Workspace)/publish/$(project)'
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure DevOps'
    appType: 'webAppLinux'
    WebAppName: 'ubi-aspnet-core-sample'
    packageForLinux: '$(Pipeline.Workspace)/publish/$(project)/**/*.zip'
